### ISSUE TITLE
Implement assert  and _assert variants that release heap lock before aborting

### ISSUE THREAD

**Issue by StevenLevine** [bitwiseworks/libc#130]
libcn can abort while holding a heap locks when an assertion fails.  In a simple, single thread application when _assert calls abort while holding 
such a lock, the process can usually shut down cleanly.

However, in a more complicated multi-thread application this often results in the application hung in the exit list because some other thread is waiting on the lock.

We have seen this occur a number of times in _um_crumb_free_maybe_lock, but it has occurred for other assertion failures as well.

This feature request requests that libc implement an assert_locked macro and an _assert_locked function which passes a pointer to the lock handle that will be freed before abort is called if the assertion fails.  A NULL pointer will indicate that there is no lock handle to be freed.

This assert_locked would replace the existing assert calls where the code knows if a lock is held, such as _um_crumb_free_maybe_lock.

Functions such as_um_lump_free_maybe_lock will pass assert_lock a NULL lock handle pointer if it was not requested to acquire the lock.

These enhancements will give that application a vastly better chance of shutting down without hanging in the exit list.

Rather than implementing the assert variants, it might be simpier to modify the existing assert and _assert to always pass a pointer to a lock handle or a NULL pointer if there is no lock handle.  This will no effect on execution time if the assertion succeeds.

**Comment by dmik** [comment]
Steven, is there any simple test case that can reproduce the issue?

**Comment by dmik** [comment]
Instead of adding a global public assert as you suggest, I'm leaning to adding `_um_assert`, specific to the heap code because this procedure of unlocking in this case is heap lock specific.

If we really want a generic solution, we need to add something like `assert_cb(exp, callback, arg)` where `callback` will be called with `arg` right before calling `abort`, if `exp` evaluates to `false`. But I'm not sure we need this. Do you know other cases except the heap where we could need this?

**Comment by dmik** [comment]
BTW, another idea which doesn't require any code changes. We can build LIBC with `NDEBUG` defined in release mode. This will effectively disable all assert code together with this problem. Still, a failing app or a test case would greatly help here.

**Comment by dmik** [comment]
I fixed all assertions I could find. The test build of LIBCn seems to work locally under heavy Samba load but a real test case which would hang in `_um_crumb_free_maybe_lock ` is still needed to check this fix properly.

**Comment by StevenLevine** [comment]
Sorry for the late reply.  Things have gotten more than a little overloaded here in the last couple of days.

I agree that _um_assert is a good solution.  I took a quick look at your commit and it looks fine to me.

I do not think that building with NDEBUG is a good idea in this case.  It would make failures caused by these kinds of heap corruption that much harder to debug.

I don't have a ready to use testcase built, but it might be possible to construct one based on an issue that Paul and I worked on recently.  However, building a simple testcase is not so simple.

While building QtDeclarative, qmake failed with a defect that caused the assert that used to be at ialloc.c#116 trigger.  An unrelated buffer overrun resulted in the lump header getting corrupted.  The next time the free list was accessed the assert triggered with the heap locked.  The lock did not cause any additional problems, probably because qmake is not multi-threaded.

FWIW, Paul and I are working on another heap corruption trap in qmlcachegen.exe which caused the assert at what used to be ifree.c:30 in _um_free_maybe_lock to trigger.  The assert that failed was not actually in
_um_free_maybe_lock, but rather in the inlined version of _um_free_maybe_lock in  _um_crumb_free_maybe_lock.

The results are a quite different because the heap corruption was sufficient to cause the mutex request to fail and for _fmutex_abort to be invoked.  At this point in time, I can't think of anything simple we can do to harden libc for this kind of corruption.

I am attaching the exceptq reports for posterity.  One for the qmake failure and two for the qmlcachegen failure.

[6797766b-0c3c_01-QMAKE-exceptq.txt](https://github.com/user-attachments/files/18760081/6797766b-0c3c_01-QMAKE-exceptq.txt)

[67a50c02-004d_01-QMLCACHEGEN-exceptq.txt](https://github.com/user-attachments/files/18760097/67a50c02-004d_01-QMLCACHEGEN-exceptq.txt)

[67a50c03-004d_01-QMLCACHEGEN-exceptq.txt](https://github.com/user-attachments/files/18760099/67a50c03-004d_01-QMLCACHEGEN-exceptq.txt)

**Comment by dmik** [comment]
Yes, I agree with you about `NDEBUG` (same arguments after a bit of thinking, that's why I finally went for `_um_assert`).

So, I guess you should try all this Qt stuff with the new DLL to see how it goes. As you can see, I fixed `_um_abort` cases as well. One of them would leave the heap lock unreleased, and many other would leave a higher level init lock acquired (which could also result in a bad hang in multithreaded environments under some circumstances).

**Comment by psmedley** [comment]
I'll do a build of libcn from git asap and test

**Comment by psmedley** [comment]
OK I rebuilt libcn0.dll this morning and tested with qmlcachegen.exe

The reported error is different:
`Assertion failed: ((crumb)->x.used.parent_crate & 0x03) == 0x00, file U:/dev/lib
c/src/emx/src/lib/malloc/ifree.c, line 30

LIBC: Killed by SIGABRT
PID=0x0053 PPID=0x0052 TID=0x0001 SLOT=0x0080 PRI=0x0200 MC=0x0001 PS=0x0010
U:\DEV\QT6-DECLARATIVE-OS2-6.8.X\BUILD\BIN\QMLCACHEGEN.EXE
Creating 0053_01.TRP
Moved 0053_01.TRP to C:\var\log\app\67AF55F300081EFC-0053_01-QMLCACHEGEN-exceptq
.txt
Abort trap
`
The trap itself appears similar

**Comment by StevenLevine** [comment]
It's trapping for the same reason.  I guess the libc changes moved things around in memory sufficiently so that a different assert is triggered.  We still have something that is overwriting a heap header structure.  The good news is that the asserts give us a human readable failure report rather than just trapping.
